---
version: "3"

services:
  react-frontend:
    image: symplesims/react-notes-app:local-1.0
    container_name: react-notes-app
    restart: always
    ports:
      - 8000:80
    environment:
      - MY_KEY=MY_VALUE
    #network_mode: bridge
    networks:
      - my-bridge

networks:
  my-bridge:
    external:
      name: docker_my-bridge

# docker-compose -f ./docker-compose.yaml up -d
# docker-compose -f ./docker-compose.yaml down

